Repository iamsazid2022/hacktoberfest22, pull requests merged in 2022-10, with the labels that each got.

#8 hacktoberfest-accepted
  hacktoberfest-accepted
Labels: hacktoberfest-accepted

#9 Changes in Content HTML
  index.html
Labels: hacktoberfest-accepted

#10 Light Weight changes in CSS
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#11 Changes in JS
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#12 Updated UI
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#13 Update style.css
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#14 Update style.css
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#15 Update index.html
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
